/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package doomaykacheckstylecriticplugin;

import org.gradle.api.Project;
import org.gradle.tooling.GradleConnectionException;
import org.gradle.api.Plugin;

public class DoomaykaCheckStyleCriticPluginPlugin implements Plugin<Project> {
    public void apply(Project project) {

        // Create extension for plugin
        DoomaykaCheckStyleCriticPluginExtension extension = project.getExtensions().create("CheckStyleCritic",
                DoomaykaCheckStyleCriticPluginExtension.class);

        // Register a task
        project.getTasks().register("parseReport", task -> {
            task.doLast(s -> App.start(project, extension));
        });
    }
}
